### PR TITLE
Merge main branch into production

### PR DESCRIPTION
**Pull request by eclipsewebmaster**

### CODE REVIEW

**Comment by amvanbaren** [comment]
@eclipsewebmaster Please make a database backup before deploying. Also make sure that ehcache is configured to write to disk, so that the cache doesn't get flooded (if it's in-memory it will).

**Comment by eclipsewebmaster** [comment]
I've already created a backup.  As for ehcache I don't think we're running that, and the only reference Mikael could find was here: https://github.com/EclipseFdn/open-vsx.org/blob/main/configuration/application.yml#L19 , but we don't know where that comes from.

**Comment by amvanbaren** [comment]
@eclipsewebmaster The current image on the `main` branch is not an official `openvsx` build. The `ehcache` property refers to this configuration file: https://github.com/amvanbaren/openvsx/blob/bugfix/extension-versions-transactional/server/src/main/resources/ehcache.xml

**Comment by eclipsewebmaster** [comment]
Ok, so should I abandon this merge then?

**Comment by amvanbaren** [comment]
@eclipsewebmaster Yes, let's abandon the merge. I'll change the ehcache.xml to write to disk, merge the branch into https://github.com/eclipse/openvsx and update the https://github.com/EclipseFdn/open-vsx.org Dockerfile

**Comment by amvanbaren** [comment]
@eclipsewebmaster However you do need to tweak the ehcache.xml to play nice with Kubernetes: https://medium.com/upstream-engineering/distributed-ehcache-on-kubernetes-3887516b1cc4

**Pull request closed without merging**
