### PR TITLE
Deploy upload fails with an Internal Server Error

### PR DESCRIPTION
**Pull request by amvanbaren**
Deploy upload fails with an Internal Server Error

### CODE REVIEW

**Comment by toddewilliams** [comment]
Can you provide an estimate of when this change will be deployed to the public servers please?

**Comment by amvanbaren** [comment]
> 
> 
> Can you provide an estimate of when this change will be deployed to the public servers please?

The goal is to deploy this change tomorrow morning, early after noon (13:00) at the latest.

**Comment by mbarbero** [comment]
> Can you provide an estimate of when this change will be deployed to the public servers please?

It's now live.

**Comment by toddewilliams** [comment]
And we have verified the fix by updating the CodeTogether listing to [CodeTogether 5.0](https://codetogether.com). Thanks all!

The users of VSCodium, GitPod, OpenVSCode Server, code-server, Coder, Eclipse Theia, and other VS Code-variants  appreciate it.

**Pull request merged**
