### PR TITLE
Infra 4049 - Open-VSX Registry Website Terms of Use

### PR DESCRIPTION
**Pull request by flora8984461**
Fix https://foundation.eclipse.org/infrazilla/show_bug.cgi?id=4049

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Review by spoenemann — COMMENTED** [review]
Great! You also need to add `/terms-of-use` to the list of routes recognized by the server:

https://github.com/EclipseFdn/open-vsx.org/blob/3e43a3dfc6074a163c9e5286094acdd31f0bee3c/configuration/application.yml#L50

This is to enable opening that path as entry point.

**Comment by chrisguindon** [comment]
@spoenemann What is the process for getting this merged in?

I plan on pushing these commits to the master branch to allow Sharon to review via the staging server so I am thinking that this PR should be made against the production branch and not master.

Is that correct?

**Comment by chrisguindon** [comment]
@flora8984461 Can you re-create this PR but make it against the production branch?

**Comment by spoenemann** [comment]
We haven't sorted out any process for PRs on this repository yet. I think that's something you and @mbarbero can just decide.

**Pull request merged**
