### PR TITLE
Infra 4049 - Open-VSX Registry Website Terms of Use

### PR DESCRIPTION
**Pull request by flora8984461**
Fix https://foundation.eclipse.org/infrazilla/show_bug.cgi?id=4049

Signed-off-by: Yi Liu <yi.liu@eclipse-foundation.org>

### CODE REVIEW

**Review by spoenemann — APPROVED** [review]
Looks good, thanks!
Just one remark: the publisher agreement page was implemented by dynamically translating a Markdown page that is fetched from the server ([documents](https://github.com/EclipseFdn/open-vsx.org/tree/master/website/static/documents) subpath). Could it make sense to do the same with the terms of use? Markdown is easier to write and maintain compared to JSX.

**Comment by flora8984461** [comment]
> Looks good, thanks!
> Just one remark: the publisher agreement page was implemented by dynamically translating a Markdown page that is fetched from the server ([documents](https://github.com/EclipseFdn/open-vsx.org/tree/master/website/static/documents) subpath). Could it make sense to do the same with the terms of use? Markdown is easier to write and maintain compared to JSX.

Sorry, did not notice there was this great usage. Please hold on a moment, I'm going to update the PR. Thx!

**Comment by flora8984461** [comment]
Updated: 

Use markdown instead of jsx for terms of use.

**Review by spoenemann — APPROVED** [review]
:+1:

**Comment by flora8984461** [comment]
@chrisguindon  I got +1 from Sharon https://foundation.eclipse.org/infrazilla/show_bug.cgi?id=4049#c22

**Pull request merged**
