### PR TITLE
Update banner

### PR DESCRIPTION
**Pull request by kineticsquid**
Update banner with message about open-vsx.org sustainability

### CODE REVIEW

**Comment by kineticsquid** [comment]
@amvanbaren @spoenemann Would you take a look at this. We need to update the banner on open-vsx.org. I'm not a TypeScript developer but it seemed pretty straightforward to modify the banner that was there. I'd like to get this updated and published as soon as possible. Thanks.

**Comment by amvanbaren** [comment]
@kineticsquid I think you also need to change the cookie key `open-vsx-whitepaper` on line 123 to e.g. `open-vsx-contribute`, because else people that have closed the whitepaper banner in the past won't see this new banner.

**Comment by kineticsquid** [comment]
@amvanbaren How's this?

**Comment by amvanbaren** [comment]
> @amvanbaren How's this?

@kineticsquid Looks good! 👍

**Pull request merged**
