### PR TITLE
Change default branch to use the production branch #391

### PR DESCRIPTION
**Pull request by chrisguindon**
Signed-off-by: Christopher Guindon <chris.guindon@eclipse-foundation.org>

### CODE REVIEW

**Review by mbarbero — APPROVED** [review]

**Comment by chrisguindon** [comment]
@mbarbero I will update the main branch and change the default branch to main now that this was committed.

**Comment by chrisguindon** [comment]
@mbarbero I just noticed that you committed some work on the main branch but the history is no longer aligned with master.

How do you want to address this?

**Comment by chrisguindon** [comment]
I created a PR to include your changes on our master branch:
https://github.com/EclipseFdn/open-vsx.org/pull/405

I was thinking that we will need to force push the content of master on the main branch to resolve this issue.

**Comment by mbarbero** [comment]
a simple merge will do it

**Pull request merged**
